server:
  port: 9000
  servlet:
    context-path: /api
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm
  profiles:
    active:
      - dbDev

springdoc:
  swagger-ui:
    path: /
    csrf:
      enabled: true